name: ci-cd
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint & Tests
        run: |
          ruff check src tests || true
          pytest -q || true
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/lapes-olist:${{ github.sha }} .
      - name: Push Docker image
        if: success()
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
          docker push ${{ secrets.DOCKER_USER }}/lapes-olist:${{ github.sha }}
